spring:
  application:
    name: distributed-job-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler
    username: scheduler
    password: scheduler

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 9800